version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rpps_postgres
    restart: always
    environment:
      POSTGRES_DB: rpps_db
      POSTGRES_USER: rpps_user
      POSTGRES_PASSWORD: rpps_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data: {}
